apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-local-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-local-app
  template:
    metadata:
      labels:
        app: my-local-app
    spec:
      containers:
      - name: app
        image: kumarnihar67/ci-cd-project:latest
        ports:
          - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: my-local-app-service
spec:
  type: NodePort
  selector:
    app: my-local-app
  ports:
    - port: 5000
      targetPort: 5000

      nodePort: 30001
